### ISSUE TITLE
[问题]: 1.21.1无法正确安装插件

### ISSUE THREAD

**Issue by sdfsfsk** [MCStarrySky/TrMenu#5]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

![Image_1726064729142](https://github.com/user-attachments/assets/7840c7af-3a1f-45d2-bc8e-625b0e679514)

### 🔍 详细的描述

```
1. ...
2. ...
3. ...
```

### 🗄 服务端日志

```

```

### ⚙ 配置文件

```

```

**Comment by sdfsfsk** [comment]
qq3082891408

**Comment by Micalhl** [comment]
<img width="787" alt="image" src="https://github.com/user-attachments/assets/f42f7dd0-37c0-4cda-b344-e94a4c022e79">

这下面还有内容吗？如果有的话能发我一下吗。
另外按照要求发一下你服务端的详情信息，服务端核心名称与版本，Java 版本等。

**Comment by sdfsfsk** [comment]
![图片](https://github.com/user-attachments/assets/4ffd6184-4124-4630-bb1d-c44636646fa8)

**Comment by sdfsfsk** [comment]
[Uploading latest.log…]()

**Comment by Micalhl** [comment]
请降级至 Java 21。
